#服务器端口配置（单机半配置）
#server:
#  port: 7001
#
#eureka:
#  instance:
#    hostname: localhost   #eureka服务端的实例名称
#  client:
#    register-with-eureka: false #false表示不向注册中心注册自己，其实就是表示我是管理微服务的我是微服务，我不需要向我自己去注册
#    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务需要依赖这个地址

#eureka集群配置
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己，其实就是表示我是管理微服务的我是微服务，我不需要向我自己去注册
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务需要依赖这个地址
